---
- name: Install apache
  hosts: all
  gather_facts: yes
  tasks:
    - name: latest version Apache
      when:
        - ansible_distribution == "CentOS"
      yum: 
        name: httpd
        state: latest
      register: apache_install

    - name: copy application files
      copy:
       src: ../app/index.html
       dest: /var/www/html/
       owner: apache
       group: apache
       mode: '0644'

    - name: start and enable httpd
      when:
        - apache_install succeeded
      systemd: 
        name: httpd
        state: started
        enabled: yes